In [1]:
import numpy as np

import matplotlib

import matplotlib.pyplot as plt

import matplotlib.patches as mpatches

import pandas as pd

import sklearn

from sklearn import neighbors # how methods are imported

from sklearn import metrics

In [2]:
LearningSet = pd.read_csv('./datasets/Type_Dataset.csv')
LearningSet.head()

,699.292969,700.611694,701.93042,703.249146,704.567871,705.886597,707.205322,708.524048,709.842773,711.161499,...,2989.832031,2991.150635,2992.469238,2993.787842,2995.106445,2996.425049,2997.743652,2999.062256,3000.380859,FermentType
0,6142.791504,6155.414063,6214.666992,6220.520508,6188.321289,6187.010254,6228.089844,6150.685547,6233.203613,6358.357422,...,16948.878906,17024.113281,16949.126953,16974.804688,16884.625000,17023.873047,17034.542969,17024.511719,17026.783203,1
1,25127.228516,25417.554688,25264.958984,25127.541016,25269.074219,25500.832031,25529.582031,25705.591797,25653.441406,25791.187500,...,69212.265625,69097.406250,69264.109375,69109.093750,68975.976563,68914.828125,69184.054688,68961.882813,68895.226563,0
2,4864.333984,4875.554199,5024.854004,5019.275391,4942.544922,4943.130859,5042.284668,5074.046875,5057.982422,4996.868652,...,13868.141602,13961.968750,14081.843750,13838.151367,13872.698242,13899.260742,13872.836914,13981.047852,14002.449219,1
3,2931.972168,2915.141602,2890.473389,2929.591064,2961.412354,2960.699463,2946.898438,2846.284424,2897.348389,2930.167480,...,7453.932617,7376.190430,7450.610352,7490.891602,7399.785156,7416.191895,7415.355469,7366.309570,7362.158203,1
4,8848.097656,8776.569336,8800.162109,8733.386719,8798.911133,8913.394531,8829.307617,8901.091797,8929.217773,8812.481445,...,22417.957031,22568.523438,22354.376953,22161.117188,22369.539063,22515.630859,22426.234375,22470.734375,22497.078125,1

In [3]:
LearningSet=LearningSet.sample(frac = 1) #shuffles data

In [5]:
LearningSet.describe()

,699.292969,700.611694,701.93042,703.249146,704.567871,705.886597,707.205322,708.524048,709.842773,711.161499,...,2989.832031,2991.150635,2992.469238,2993.787842,2995.106445,2996.425049,2997.743652,2999.062256,3000.380859,FermentType
count,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,...,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000
mean,7605.108227,7619.414142,7634.500476,7655.468829,7680.946753,7701.486353,7716.180982,7756.997083,7757.456354,7772.706873,...,20929.930249,20895.017285,20964.669507,20944.156372,20904.859814,20928.489038,20933.589673,20894.242554,20885.018286,0.800000
std,7185.733697,7233.943833,7227.176830,7225.743670,7262.444547,7308.415979,7318.081780,7329.491054,7311.832103,7330.604464,...,19600.992933,19520.808843,19607.373151,19632.730103,19503.283590,19522.493025,19588.051194,19562.106120,19552.368935,0.410391
min,1929.100586,1940.320923,1977.642578,1970.822388,1946.000732,1912.339844,1878.048828,1951.274170,1920.654907,1926.547852,...,6110.365723,6246.152344,6219.704102,6229.123535,6192.971191,6275.705078,6275.164063,6210.084473,6189.952148,0.000000
25%,3253.624756,3247.313232,3244.662537,3257.631286,3293.453247,3320.916076,3300.760193,3264.259278,3335.423279,3383.783447,...,8964.907104,8939.075439,9031.378418,9055.461182,9040.375244,9007.631836,9013.464233,8974.678955,8954.349121,1.000000
50%,4569.179931,4550.946777,4680.141846,4664.789551,4610.443603,4629.590087,4700.208496,4743.867920,4740.404053,4668.764160,...,13289.203613,13294.024903,13406.612305,13212.947754,13301.851074,13396.192383,13320.364258,13285.529785,13283.894043,1.000000
75%,8812.630860,8789.291016,8801.315185,8767.540039,8828.759522,8923.912109,8881.787109,8909.129150,8947.800537,8870.526123,...,23204.392090,23341.640626,23172.616699,23092.964356,23168.473145,23296.718261,23183.626953,23203.084473,23224.463379,1.000000
max,25653.939453,25806.816406,25976.070313,26130.564453,26203.146484,26193.087891,26172.089844,26204.019531,26174.441406,26130.244141,...,75002.593750,74488.843750,75274.242188,75517.343750,74631.507813,74822.820313,75094.710938,74934.375000,74877.671875,1.000000

In [6]:
TrainSet =  LearningSet.iloc[:15,:] #.iloc is used to slice data frames using positional indices

TestSet = LearningSet.iloc[15:,:]

In [7]:
Xtrain = TrainSet.drop(['FermentType'],axis=1) 

Xtest = TestSet.drop(['FermentType'],axis=1)

In [8]:
ytrain = TrainSet.FermentType #This contains the ground truth label, or output
ytest = TestSet.FermentType

In [9]:
model = neighbors.KNeighborsClassifier(n_neighbors = 3)

In [10]:
model.fit(Xtrain.iloc[:,:],ytrain)

ytestpred = model.predict(Xtest.iloc[:,:])

In [11]:
ytestpred, ytest.values #compare

(array([1, 1, 1, 1, 1], dtype=int64), array([0, 1, 1, 1, 1], dtype=int64))

In [12]:
print(metrics.accuracy_score(ytrain, model.predict(Xtrain.iloc[:,:]))) #This compares the true labels for the train set with the predicted labels for the train set

print(metrics.accuracy_score(ytest, model.predict(Xtest.iloc[:,:]))) #This compares the true labels for the test set with the predicted labels for the test set
                                                                      #(same t

0.8
0.8

In [13]:
print(metrics.recall_score(ytest, model.predict(Xtest.iloc[:,:])))

1.0

In [14]:
from sklearn.model_selection import cross_val_predict, cross_val_score, cross_validate
from sklearn.model_selection import KFold, StratifiedKFold

In [18]:
# This is the standard version. Important: it doesn't shuffle the data,
# so if your positive examples are all at the beginning or all the end, it might lead to disastrous results.

cv1 = KFold(n_splits = 4)

#This is v2: shuffling added (recommended!)

cv2 = KFold(shuffle = True, n_splits = 4, random_state=5)

# STRATIFICATION ensures that the class distributions in each split resembles those of the
# entire data set

cv3 = StratifiedKFold(shuffle = True, n_splits = 4, random_state=5)

In [19]:
final_features=LearningSet.drop(['FermentType'],axis=1) #But label
targets=LearningSet.FermentType

scores2 = cross_validate(model, final_features, targets, cv = cv2, scoring='accuracy')

scores3 = cross_validate(model, final_features, targets, cv = cv3, scoring='accuracy')

In [21]:
print("{:.3f}".format(scores2['test_score'].mean()), "{:.3f}".format(scores2['test_score'].std()))
print("{:.3f}".format(scores3['test_score'].mean()), "{:.3f}".format(scores3['test_score'].std()))

0.800 0.141
0.800 0.000